{
 "title": "EndpointLatency",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "All", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum[$__rate_interval])/rate(response_latency_seconds_count[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per Region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "eu-west-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"eu-west-1\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"eu-west-1\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "og.local",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"og.local\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"og.local\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eu-central-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"eu-central-1\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"eu-central-1\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "eu-west-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"eu-west-2\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"eu-west-2\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "us-east-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"us-east-1\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"us-east-1\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "us-west-1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"us-west-1\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"us-west-1\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "us-east-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"us-east-2\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"us-east-2\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "us-west-2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{region=\"us-west-2\"}[$__rate_interval])/rate(response_latency_seconds_count{region=\"us-west-2\"}[$__rate_interval])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per Endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "https://api.binance.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{endpoint=\"https://api.binance.com\"}[$__rate_interval])/rate(response_latency_seconds_count{endpoint=\"https://api.binance.com\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://api1.binance.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{endpoint=\"https://api1.binance.com\"}[$__rate_interval])/rate(response_latency_seconds_count{endpoint=\"https://api1.binance.com\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://api2.binance.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{endpoint=\"https://api2.binance.com\"}[$__rate_interval])/rate(response_latency_seconds_count{endpoint=\"https://api2.binance.com\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://api3.binance.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{endpoint=\"https://api3.binance.com\"}[$__rate_interval])/rate(response_latency_seconds_count{endpoint=\"https://api3.binance.com\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "https://api-gcp.binance.com",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(response_latency_seconds_sum{endpoint=\"https://api-gcp.binance.com\"}[$__rate_interval])/rate(response_latency_seconds_count{endpoint=\"https://api-gcp.binance.com\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}